language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-17
    - extra-google-google_play_services

addons:
  sonarcloud:
    organization: "amrabed-github"

script:
  - sonar-scanner